#!/bin/bash
# ============================================================
# TellSafe — Quick Setup Script
# Run: chmod +x setup.sh && ./setup.sh
# ============================================================

set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo -e "${BOLD}🛡️  TellSafe Setup${NC}"
echo -e "   Anonymous Feedback for Communities"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ============================================================
# Step 1: Check prerequisites
# ============================================================
echo -e "${CYAN}[1/8]${NC} Checking prerequisites..."

# Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}✗ Node.js not found. Install from https://nodejs.org${NC}"
    exit 1
fi
NODE_VERSION=$(node -v)
echo -e "  ${GREEN}✓${NC} Node.js $NODE_VERSION"

# npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}✗ npm not found${NC}"
    exit 1
fi
echo -e "  ${GREEN}✓${NC} npm $(npm -v)"

# Firebase CLI
if ! command -v firebase &> /dev/null; then
    echo -e "  ${YELLOW}⚠ Firebase CLI not found. Installing...${NC}"
    npm install -g firebase-tools
fi
echo -e "  ${GREEN}✓${NC} Firebase CLI $(firebase --version)"

echo ""

# ============================================================
# Step 2: Install dependencies
# ============================================================
echo -e "${CYAN}[2/8]${NC} Installing dependencies..."
npm install --silent
echo -e "  ${GREEN}✓${NC} Main dependencies installed"

cd functions
npm install --silent
cd ..
echo -e "  ${GREEN}✓${NC} Cloud Functions dependencies installed"
echo ""

# ============================================================
# Step 3: Firebase login check
# ============================================================
echo -e "${CYAN}[3/8]${NC} Checking Firebase authentication..."
if ! firebase projects:list &> /dev/null; then
    echo -e "  ${YELLOW}Opening browser for Firebase login...${NC}"
    firebase login
fi
echo -e "  ${GREEN}✓${NC} Authenticated with Firebase"
echo ""

# ============================================================
# Step 4: Select or create Firebase project
# ============================================================
echo -e "${CYAN}[4/8]${NC} Firebase project setup"
echo ""
echo "  Your Firebase projects:"
firebase projects:list 2>/dev/null | head -20
echo ""
read -p "  Enter your Firebase project ID (or 'new' to create one): " PROJECT_ID

if [ "$PROJECT_ID" = "new" ]; then
    read -p "  Enter a project ID (e.g., tellsafe-prod): " PROJECT_ID
    echo -e "  ${YELLOW}Creating project...${NC}"
    firebase projects:create "$PROJECT_ID" --display-name "TellSafe"
fi

firebase use "$PROJECT_ID"
echo -e "  ${GREEN}✓${NC} Using project: $PROJECT_ID"
echo ""

# ============================================================
# Step 5: Generate encryption key
# ============================================================
echo -e "${CYAN}[5/8]${NC} Generating encryption key..."
ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
echo -e "  ${GREEN}✓${NC} Key generated"
echo ""

# ============================================================
# Step 6: Create .env.local
# ============================================================
echo -e "${CYAN}[6/8]${NC} Setting up environment variables"
echo ""

if [ -f .env.local ]; then
    echo -e "  ${YELLOW}⚠ .env.local already exists. Skipping.${NC}"
else
    echo "  You'll need your Firebase web app config values."
    echo "  Find them at: Firebase Console → Project Settings → Web App"
    echo ""

    read -p "  FIREBASE_API_KEY: " FB_API_KEY
    read -p "  FIREBASE_AUTH_DOMAIN (e.g., ${PROJECT_ID}.firebaseapp.com): " FB_AUTH_DOMAIN
    FB_AUTH_DOMAIN=${FB_AUTH_DOMAIN:-"${PROJECT_ID}.firebaseapp.com"}
    read -p "  FIREBASE_STORAGE_BUCKET (e.g., ${PROJECT_ID}.appspot.com): " FB_STORAGE
    FB_STORAGE=${FB_STORAGE:-"${PROJECT_ID}.appspot.com"}
    read -p "  FIREBASE_MESSAGING_SENDER_ID: " FB_SENDER
    read -p "  FIREBASE_APP_ID: " FB_APP_ID

    cat > .env.local << EOF
# TellSafe Environment Variables
# Generated by setup.sh on $(date)

# Firebase Client (public)
NEXT_PUBLIC_FIREBASE_API_KEY=$FB_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FB_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$FB_STORAGE
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$FB_SENDER
NEXT_PUBLIC_FIREBASE_APP_ID=$FB_APP_ID

# Firebase Admin (server-side only)
# Download service account key from Firebase Console → Project Settings → Service Accounts
# Then paste the JSON here (or set GOOGLE_APPLICATION_CREDENTIALS path)
FIREBASE_SERVICE_ACCOUNT_KEY=

# Relay Encryption Key (server-side only)
TELLSAFE_RELAY_ENCRYPTION_KEY=$ENCRYPTION_KEY

# SendGrid (add later)
SENDGRID_API_KEY=

# Anthropic / Claude API (add later for sentiment analysis)
ANTHROPIC_API_KEY=

# Stripe (add later for payments)
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=

# App URL (update after Vercel deploy)
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

    echo -e "  ${GREEN}✓${NC} .env.local created"
    echo ""
    echo -e "  ${YELLOW}⚠ IMPORTANT: You still need to add FIREBASE_SERVICE_ACCOUNT_KEY${NC}"
    echo "  Download it from Firebase Console → Project Settings → Service Accounts"
    echo "  → Generate new private key → paste the JSON into .env.local"
fi
echo ""

# ============================================================
# Step 7: Deploy Firestore rules + indexes
# ============================================================
echo -e "${CYAN}[7/8]${NC} Deploying Firestore rules and indexes..."

# Enable Firestore API if needed
echo -e "  Deploying security rules..."
firebase deploy --only firestore:rules 2>/dev/null || echo -e "  ${YELLOW}⚠ Rules deploy failed — you may need to enable Firestore in the console first${NC}"

echo -e "  Deploying indexes..."
firebase deploy --only firestore:indexes 2>/dev/null || echo -e "  ${YELLOW}⚠ Index deploy failed — indexes will build on first query${NC}"

echo -e "  Deploying storage rules..."
firebase deploy --only storage 2>/dev/null || echo -e "  ${YELLOW}⚠ Storage rules deploy failed — enable Storage in console first${NC}"

echo ""

# ============================================================
# Step 8: Done!
# ============================================================
echo -e "${CYAN}[8/8]${NC} Setup complete!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}${BOLD}🎉 TellSafe is ready!${NC}"
echo ""
echo "  Next steps:"
echo ""
echo -e "  ${BOLD}1. Add your Firebase service account key:${NC}"
echo "     Firebase Console → Project Settings → Service Accounts"
echo "     → Generate new private key → paste JSON into .env.local"
echo ""
echo -e "  ${BOLD}2. Enable Firebase services in the console:${NC}"
echo "     • Authentication → Email/Password sign-in"
echo "     • Firestore Database → Create database (production mode)"
echo "     • Storage → Get started"
echo ""
echo -e "  ${BOLD}3. Start the dev server:${NC}"
echo -e "     ${CYAN}npm run dev${NC}"
echo ""
echo -e "  ${BOLD}4. Create your account:${NC}"
echo "     Open http://localhost:3000/auth/signup"
echo ""
echo -e "  ${BOLD}5. Test the feedback form:${NC}"
echo "     Open http://localhost:3000/{your-slug}"
echo ""
echo -e "  ${BOLD}6. Deploy to Vercel:${NC}"
echo -e "     ${CYAN}git add . && git commit -m 'Initial launch' && git push${NC}"
echo "     Then import the repo at vercel.com/new"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "  📖 Full guide: ${CYAN}DEPLOY.md${NC}"
echo -e "  🛡️ Encryption key saved to .env.local"
echo -e "  🔥 Firebase project: ${BOLD}$PROJECT_ID${NC}"
echo ""
